kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: arm64
trigger:
  event:
    - push
    - pull_request
steps:
  - name: build shared lib1
    image: moby/buildkit:master-rootless
    commands:
      - buildctl-daemonless.sh build --progress plain
        --output type=image,name=registry.swerik.dev/youtubedownloader/shared:builder,push=true
        --import-cache type=registry,ref=registry.swerik.dev/youtubedownloader/shared:builder
        --import-cache type=registry,ref=registry.swerik.dev/youtubedownloader/shared:latest
        --export-cache type=inline
        --frontend=dockerfile.v0
        --local context=Shared
        --local dockerfile=Shared
        --opt target=tester
    environment:
      BUILDCTL_CONNECT_RETRIES_MAX: 1000
  
  - name: build shared lib
    image: plugins/docker
    settings:
      dockerfile: Shared/Dockerfile
      context: Shared
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/shared
      cache_from:
        - registry.swerik.dev/youtubedownloader/shared:builder
        - registry.swerik.dev/youtubedownloader/shared:latest
      tags: builder
      target: tester
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
      build_args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      DOCKER_BUILDKIT: 1

  - name: build backend
    image: plugins/docker
    settings:
      dockerfile: Backend/Dockerfile
      context: Backend
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/backend
      cache_from:
        - registry.swerik.dev/youtubedownloader/backend:builder
        - registry.swerik.dev/youtubedownloader/backend:latest
      tags: builder
      target: tester
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    depends_on:
      - build shared lib
    environment:
      DOCKER_BUILDKIT: 1

  - name: build frontend
    image: plugins/docker
    settings:
      dockerfile: Frontend/Dockerfile
      context: Frontend
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/frontend
      cache_from:
        - registry.swerik.dev/youtubedownloader/frontend:builder
        - registry.swerik.dev/youtubedownloader/frontend:latest
      tags: builder
      target: tester
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    depends_on:
      - build shared lib
    environment:
      DOCKER_BUILDKIT: 1
---
kind: pipeline
type: docker
name: build Deploy Images
depends_on:
  - build
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
steps:
  - name: build shared lib
    image: plugins/docker
    settings:
      dockerfile: Shared/Dockerfile
      context: Shared
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/shared
      cache_from:
        - registry.swerik.dev/youtubedownloader/shared:latest
        - registry.swerik.dev/youtubedownloader/shared:builder
      tags: latest
      target: final
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD

  - name: build backend
    image: plugins/docker
    settings:
      dockerfile: Backend/Dockerfile
      context: Backend
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/backend
      cache_from:
        - registry.swerik.dev/youtubedownloader/backend:latest
        - registry.swerik.dev/youtubedownloader/backend:builder
      tags: latest
      target: final
      build_args:
        DOCKER_BUILDKIT: 1
      build_args_from_env:
        DOCKER_BUILDKIT: 1
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    depends_on:
      - build shared lib
    environment:
      DOCKER_BUILDKIT: 1

  - name: build frontend
    image: plugins/docker
    settings:
      dockerfile: Frontend/Dockerfile
      context: Frontend
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/frontend
      cache_from:
        - registry.swerik.dev/youtubedownloader/frontend:latest
        - registry.swerik.dev/youtubedownloader/frontend:builder
      tags: latest
      target: final
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    depends_on:
      - build shared lib
---
kind: pipeline
type: ssh
name: Deploy
depends_on:
  - build Deploy Images
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
server:
  host: erikpi
  user:
    from_secret: SSH_USERNAME
  password:
    from_secret: SSH_PASSWORD
steps:
  - name: docker login & Deploy
    commands:
      - docker --config /home/drone/.docker login localhost:5000 -u $USERNAME -p $PASSWORD
      - docker --config /home/drone/.docker compose up -d --pull always
    environment:
      USERNAME:
        from_secret: REGISTRY_USERNAME
      PASSWORD:
        from_secret: REGISTRY_PASSWORD