kind: pipeline
type: docker
name: test
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
    - test/old-commit
steps:
  - name: run tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    commands:
      - dotnet test
---
kind: pipeline
type: docker
name: build Deploy Images
depends_on:
  - test
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
    - test/old-commit
steps:
  - name: build Backend
    image: plugins/docker
    settings:
      dockerfile: Backend/Dockerfile
      context: .
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/backend
      tags: latest
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    environment:
      DOCKER_BUILDKIT: 1

  - name: build Frontend
    image: plugins/docker
    settings:
      dockerfile: Frontend/Dockerfile
      context: .
      registry: registry.swerik.dev
      repo: registry.swerik.dev/youtubedownloader/frontend
      tags: latest
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    environment:
      DOCKER_BUILDKIT: 1

  - name: parallelism
    image: alpine
    commands:
      - echo finished
    depends_on:
      - build Backend
      - build Frontend
---
kind: pipeline
type: ssh
name: Deploy
depends_on:
  - build Deploy Images
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
    - test/old-commit
server:
  host: erikpi
  user:
    from_secret: SSH_USERNAME
  password:
    from_secret: SSH_PASSWORD
steps:
  - name: docker login & Deploy
    commands:
      - docker --config /home/drone/.docker login localhost:5000 -u $USERNAME -p $PASSWORD
      - docker --config /home/drone/.docker compose up -d --pull always
    environment:
      USERNAME:
        from_secret: REGISTRY_USERNAME
      PASSWORD:
        from_secret: REGISTRY_PASSWORD