kind: pipeline
type: docker
name: build
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
steps:        
  - name: build shared lib
    image: plugins/docker
    settings:
      dockerfile: Shared/Dockerfile
      context: Shared
      registry: $DOCKER_HOST_REGISTRY:5000
      repo: $DOCKER_HOST_REGISTRY:5000/youtubedownloader/shared
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD

  - name: build backend
    image: plugins/docker
    settings:
      dockerfile: Backend/Dockerfile
      context: Backend
      registry: localhost:5000
      repo: localhost:5000/youtubedownloader/backend
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    depends_on:
      - build shared lib

  - name: build frontend
    image: plugins/docker
    settings:
      dockerfile: Frontend/Dockerfile
      context: Frontend
      registry: localhost:5000
      repo: localhost:5000/youtubedownloader/frontend
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    depends_on:
      - build shared lib
---
kind: pipeline
type: ssh
name: test
depends_on:
  - build
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
server:
  host: erikpi
  user:
    from_secret: SSH_USERNAME
  password:
    from_secret: SSH_PASSWORD
steps:
  - name: docker login
    commands:
      - docker login localhost:5000 -u $USERNAME -p $PASSWORD
    environment:
      USERNAME:
        from_secret: $REGISTRY_USERNAME
      PASSWORD:
        from_secret: $REGISTRY_PASSWORD
  - name: deploy
    commands:
      - docker compose up -d