version: "3.*"
name: youtubedownloader
services:
  backend:
    container_name: youtubedownloader-backend
    image: registry.swerik.dev/youtubedownloader/backend
    networks:
      - default
    environment:
      FFMPEG_PATH: "/usr/bin/ffmpeg"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '2000M'
        reservations:
          cpus: '0.1'
          memory: '400M'
    logging:
      driver: 'json-file'
      options:
        max-size: '10M'
        max-file: '10'
  frontend:
    container_name: youtubedownloader-frontend
    image: registry.swerik.dev/youtubedownloader/frontend
    depends_on: 
      - backend
    networks:
      - default
      - proxy
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: '400M'
        reservations:
          cpus: '0.1'
          memory: '10M'
    logging:
      driver: 'json-file'
      options:
        max-size: '500k'
        max-file: '10'
networks:
  default:
    driver: bridge
  proxy:
    external: true
